---
# main.yml - Main central jump host Ansible file

- name: List Kubernetes Namespaces
  hosts: localhost
  collections:
    - amazon.aws
  gather_facts: false
  vars:
   kubernetes_clusters:
     - cluster_name: catcluster
       role: "arn:aws:iam::184527568870:role/centroid-role-catcluster20251216145250081800000002"
       node_cmds: "\"id\",\"uname -a\""
     - cluster_name: dogcluster
       role: "arn:aws:iam::184527568870:role/centroid-role-dogcluster20251216145250081900000004"
       node_cmds: "\"id\",\"uname -a\""

  tasks:
    - name: Run Commands Against Multiple Clusters
      include_tasks: loop_tasks.yml
      loop: "{{ kubernetes_clusters }}"
